name: npm publish on main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # required for npm provenance (OIDC)

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test -- --run

      - name: Build
        run: npm run build

      - name: Check if version already published
        id: check
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          echo "Package: $NAME@$VERSION"
          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "already=true" >> "$GITHUB_OUTPUT"
          else
            echo "already=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish to npm (with provenance)
        if: steps.check.outputs.already == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          npm publish --provenance --access public

      - name: Skip note
        if: steps.check.outputs.already == 'true'
        run: echo "This version is already published. Skipping npm publish."
